---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: townhall
  name: townhall
spec:
  containers:
  - image: ghcr.io/schuhu/townhall:1.0.0
    name: townhall
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: townhall
spec:
  selector:
    app: townhall
  ports:
    - protocol: TCP
      port: 8080
      name: http-townhall
